src/apps/accounts/urls.py
from django.urls import path
from apps.accounts.views import login_view, logout_view

app_name = "auth"

urlpatterns = [
    path('login/', login_view, name="login_view"),
    path('logout/', logout_view, name="logout_view")
]

src/project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.home.urls', namespace="home")),
    path('auth/', include('apps.accounts.urls', namespace="auth")),
    path('api/', include([
        path('auth/', include('project.core.apps.auth_api.urls', namespace="core")),
    ])),
]

src/templates/base_template.html
<!doctype html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="stylesheet" href="{% static 'project/css/bootstrap.min.css' %}" >
    <link rel="stylesheet" href="{% static 'project/css/style.css' %}" >

    {% block css %}
    {% endblock %}

    <title>{% block title %}{% endblock %}</title>
  </head>
  <body>
    {% block content %}
    <h1>Hello, world!</h1>

    {% endblock %}

    <script src="{% static 'project/js/jquery-3.3.1.min.js' %}" ></script>
    <script src="{% static 'project/js/popper.min.js' %}" ></script>
    <script src="{% static 'project/js/bootstrap.min.js' %}" ></script>
    <script src="{% static 'project/js/script.js' %}" ></script>

    <script>
    {% block javascript %}
    {% endblock %}
    </script>
  </body>
</html>

src/templates/index.html
{% extends 'base_template.html' %}

{% block css %}

{% endblock %}

{% block title %}Login to your account{% endblock %}

{% block content %}
<h3>{{ user }}</h3>
<a class="btn btn-sm btn-danger" href="{% url 'auth:logout_view' %}">Logout</a>
    <div class="tree well">
        <ul>
            <li>
                <span><i class="icon-folder-open"></i> Parent</span> <a href="">Goes somewhere</a>
                <ul>
                    <li>
                        <span><i class="icon-minus-sign"></i> Child</span> <a href="">Goes somewhere</a>
                        <ul>
                            <li>
                                <span><i class="icon-leaf"></i> Grand Child</span> <a href="">Goes somewhere</a>
                            </li>
                        </ul>
                    </li>
                    <li>
                        <span><i class="icon-minus-sign"></i> Child</span> <a href="">Goes somewhere</a>
                        <ul>
                            <li>
                                <span><i class="icon-leaf"></i> Grand Child</span> <a href="">Goes somewhere</a>
                            </li>
                            <li>
                                <span><i class="icon-minus-sign"></i> Grand Child</span> <a href="">Goes somewhere</a>
                                <ul>
                                    <li>
                                        <span><i class="icon-minus-sign"></i> Great Grand Child</span> <a href="">Goes somewhere</a>
                                        <ul>
                                            <li>
                                                <span><i class="icon-leaf"></i> Great great Grand Child</span> <a href="">Goes somewhere</a>
                                            </li>
                                            <li>
                                                <span><i class="icon-leaf"></i> Great great Grand Child</span> <a href="">Goes somewhere</a>
                                            </li>
                                         </ul>
                                    </li>
                                    <li>
                                        <span><i class="icon-leaf"></i> Great Grand Child</span> <a href="">Goes somewhere</a>
                                    </li>
                                    <li>
                                        <span><i class="icon-leaf"></i> Great Grand Child</span> <a href="">Goes somewhere</a>
                                    </li>
                                </ul>
                            </li>
                            <li>
                                <span><i class="icon-leaf"></i> Grand Child</span> <a href="">Goes somewhere</a>
                            </li>
                        </ul>
                    </li>
                </ul>
            </li>
            <li>
                <span><i class="icon-folder-open"></i> Parent2</span> <a href="">Goes somewhere</a>
                <ul>
                    <li>
                        <span><i class="icon-leaf"></i> Child</span> <a href="">Goes somewhere</a>
                    </li>
                </ul>
            </li>
        </ul>
    </div>

    <div class="tree">
        <ul>
            <li>
                <span><i class="icon-calendar"></i> 2013, Week 2</span>
                <ul>
                    <li>
                        <span class="badge badge-success"><i class="icon-minus-sign"></i> Monday, January 7: 8.00 hours</span>
                        <ul>
                            <li>
                                <a href=""><span><i class="icon-time"></i> 8.00</span> &ndash; Changed CSS to accomodate...</a>
                            </li>
                        </ul>
                    </li>
                    <li>
                        <span class="badge badge-success"><i class="icon-minus-sign"></i> Tuesday, January 8: 8.00 hours</span>
                        <ul>
                            <li>
                                <span><i class="icon-time"></i> 6.00</span> &ndash; <a href="">Altered code...</a>
                            </li>
                            <li>
                                <span><i class="icon-time"></i> 2.00</span> &ndash; <a href="">Simplified our approach to...</a>
                            </li>
                        </ul>
                    </li>
                    <li>
                        <span class="badge badge-warning"><i class="icon-minus-sign"></i> Wednesday, January 9: 6.00 hours</span>
                        <ul>
                            <li>
                                <a href=""><span><i class="icon-time"></i> 3.00</span> &ndash; Fixed bug caused by...</a>
                            </li>
                            <li>
                                <a href=""><span><i class="icon-time"></i> 3.00</span> &ndash; Comitting latest code to Git...</a>
                            </li>
                        </ul>
                    </li>
                    <li>
                        <span class="badge badge-important"><i class="icon-minus-sign"></i> Wednesday, January 9: 4.00 hours</span>
                        <ul>
                            <li>
                                <a href=""><span><i class="icon-time"></i> 2.00</span> &ndash; Create component that...</a>
                            </li>
                        </ul>
                    </li>
                </ul>
            </li>
            <li>
                <span><i class="icon-calendar"></i> 2013, Week 3</span>
                <ul>
                    <li>
                        <span class="badge badge-success"><i class="icon-minus-sign"></i> Monday, January 14: 8.00 hours</span>
                        <ul>
                            <li>
                                <span><i class="icon-time"></i> 7.75</span> &ndash; <a href="">Writing documentation...</a>
                            </li>
                            <li>
                                <span><i class="icon-time"></i> 0.25</span> &ndash; <a href="">Reverting code back to...</a>
                            </li>
                        </ul>
                    </li>
                </ul>
            </li>
        </ul>
    </div>
{% endblock %}

{% block javascript %}
{% endblock %}